
export const dict: any[] = [
   { "step": 1, "word": "abated", "transcription": "[əˈbeɪtəd]", "translates": ["сниженный", "ослабевший", "ослабленный"] },
   { "step": 2, "word": "abatement", "transcription": "[əˈbeɪtmənt]", "translates": ["снижение", "уменьшение", "ослабление", "скидка", "смягчение", "прекращение", "аннулирование"] },
   { "step": 3, "word": "abater", "transcription": "", "translates": ["прошение об аннулировании", "прекращении"] },
   { "step": 4, "word": "abatis", "transcription": "['æbəˌtis]", "translates": ["засека", "завал"] },
   { "step": 1, "word": "abattage", "transcription": "", "translates": ["массовое уничтожение животных", "чтобы предотвратить распространение инфекции"] },
   { "step": 1, "word": "abattoir", "transcription": "[ˈæbətwɑːr]", "translates": ["скотобойня"] },
   { "step": 1, "word": "abatvoix", "transcription": "", "translates": ["акустический экран"] },
   { "step": 1, "word": "abaxial", "transcription": "", "translates": ["абаксиальный", "направленный от оси", "на верхней поверхности листа"] },
   { "step": 1, "word": "abb", "transcription": "[æb]", "translates": ["уток", "основа ткани"] },
   { "step": 1, "word": "abba", "transcription": "", "translates": ["Авва", "Отец", "авва", "авва"] },
   { "step": 1, "word": "abbacy", "transcription": "[ˈæbˌəˌsi]", "translates": ["аббатство"] },
   { "step": 1, "word": "abbatial", "transcription": "", "translates": ["аббатский", "аббатовский"] },
   { "step": 1, "word": "abbe", "transcription": "[ˈæbi]", "translates": ["аббат", "батюшка"] },
   { "step": 1, "word": "abbess", "transcription": "[ˈæbes]", "translates": ["аббатиса", "настоятельница монастыря"] },
   { "step": 1, "word": "abbey", "transcription": "[ˈæbi]", "translates": ["аббатство", "монастырь"] },
   { "step": 1, "word": "abbot", "transcription": "[ˈæbət]", "translates": ["аббат", "настоятель монастыря"] },
   { "step": 1, "word": "abbreviate", "transcription": "[əˈbriːviˌet]", "translates": ["сокращать", "использовать сокращения", "урезать"] },
   { "step": 1, "word": "abbreviated", "transcription": "[əˈbriːviˌetəd]", "translates": ["сокращенный", "укороченный"] },
   { "step": 1, "word": "abbreviating", "transcription": "[əˈbriːviˌetɪŋ]", "translates": ["сокращение", "сокращающий"] },
   { "step": 1, "word": "abbreviation", "transcription": "[əˌbriviˈeɪʃən]", "translates": ["аббревиатура", "сокращение", "аббревиация"] },
   { "step": 1, "word": "abbreviator", "transcription": "", "translates": ["составитель папского бреве", "аббревиатор"] },
   { "step": 1, "word": "abbreviature", "transcription": "", "translates": ["сокращение", "сокращенное изложение"] },
   { "step": 1, "word": "ABC", "transcription": "[ˌeɪbiːˈsiː]", "translates": ["азбука", "алфавит", "азы", "основы", "начатки", "простой", "простейший"] },
   { "step": 1, "word": "ABC-book", "transcription": "[ˈeɪbiːˈsiːbʊk]", "translates": ["букварь"] },
   { "step": 1, "word": "abdest", "transcription": "", "translates": ["абдест", "ритуальное омовение рук перед молитвой"] },
   { "step": 1, "word": "abdicant", "transcription": "", "translates": ["человек", "отрекающийся", "отказывающийся", "отрекающийся"] },
   { "step": 1, "word": "abdicate", "transcription": "[ˈæbdəˌket]", "translates": ["отказываться", "отрекаться", "слагать полномочия"] },
   { "step": 1, "word": "abdication", "transcription": "[ˌæbdɪˈkeɪʃən]", "translates": ["отречение", "отказ", "сложение полномочий", "отказ от должности", "отказ от права"] }

];